#ifndef CONFIG_H
#define CONFIG_H

//LOGGING CONFIGURATION
#define LOGGING_ENABLED 1
#define LOGGING_DISABLED 0

//FOOBAR MODULE NAMESPACING CONFIGURATION
#define FOOBAR_NAMESPACE_DISABLED 0
#define FOOBAR_NAMESPACE_ENABLED 1

//FOOBAR MODULE SHORT NAMES FOR NAMESPACE CONFIGURATION
#define FOOBAR_SHORT_NAMES_ENABLED 1
#define FOOBAR_SHORT_NAMES_DISABLED 0

#endif